name: Github Pages Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  build:
    if: github.repository == 'bitcoinzkio/bitcoinzk-docs'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.20

      - run: bun install
      - run: bun run build --locale en

      - name: Deploy Gh-Pages ðŸš€
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: docs.bitcoinzk.io